version: "3"

services:
    sls:
        build:
            context: .
            dockerfile: Dockerfile.sls
        ports:
            - $SLS_PORT:8080/udp
            - $HTTP_STATS_PORT:8081/tcp
        volumes:
            - ./sls.conf:/srt-live-server/sls.conf
    srtla:
        build:
            context: .
            dockerfile: Dockerfile.srtla
        ports:
            - $SRTLA_PORT:5000/udp
        depends_on:
            - sls
        links:
            - sls
